### ISSUE TITLE
v1 converter support

### ISSUE THREAD

**Issue by tormath1** [coreos/ign-converter#25]
Hi,

According to the `README.md`:
> This is a tool and library for converting old (spec v1-v2.x.0) [...]

I don't see any `v1toX` in `translate/` is it something in development or not yet ? Thanks !

**Comment by bgilbert** [comment]
Spec v1 is ancient and essentially unused, so there are no plans to translate it.  I'll update the README; thanks for reporting.

**Comment by tormath1** [comment]
@bgilbert thanks for your answer ! Do you welcome PR on this repo ? I would be interested to try to provide V1 support to `ign-converter`.

With Flatcar we would like to upgrade `ignition` to v3 but keep compatibility for v2/v1 users.

**Comment by bgilbert** [comment]
Thinking about it some more, no code changes should be needed.  If you're using ign-converter as a library, just use the Ignition `spec2x` branch to parse the v1 config as a 2.4 config first.  If you're using the ign-converter command-line program, it should already handle this for you.

If that isn't working for you, please let us know.

**Comment by tormath1** [comment]
ouh that's right - v2.x does [fallback](https://github.com/coreos/ignition/blob/spec2x/config/v2_0/config.go#L47-L50) on v1. So `ign-converter` does support v1 translation, I confirmed with a local test.
Thanks for you answer. :)
